### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by tur-ium** [geofabrik/OpenRailRouting#16]
Happy now year!
I am trying to install on Windows, using cygwin. Here are the steps I took, based of the README for ORR and GraphHopper. Some errors crop up during installation:

1. Git cloned GraphHopper and set OpenJDK - all ok
2. Ran ```git submodule add https://github.com/geofabrik/OpenRailRouting.git```, and ```git submodule update```. Encountered the following error: 
```
error: Server does not allow request for unadvertised object d7497886bbb91b3cbb3
48465b1bd7308f5141ee0
Fetched in submodule path 'graphhopper', but it did not contain d7497886bbb91b3c
bb348465b1bd7308f5141ee0. Direct fetching of that commit failed.
```
3. I assumed it was not crucial so continued and ran ```bash build.sh```. Encountered the error 
```build.sh: line 2: $'\r': command not found
: invalid option name: pipefail
```
When I remove this line I get a list of error messages
```
build.sh: line 3: cd: $'graphhopper\r': No such file or directory
build.sh: line 4: mvn: command not found
build.sh: line 5: cd: $'..\r': No such file or directory
build.sh: line 6: $'\r': command not found
build.sh: line 8: cd: $'map-matching\r': No such file or directory
build.sh: line 9: mvn: command not found
build.sh: line 10: cd: $'..\r': No such file or directory
build.sh: line 11: $'\r': command not found
build.sh: line 14: cd: $'graphhopper\r': No such file or directory
build.sh: line 15: mvn: command not found
build.sh: line 16: mvn: command not found
build.sh: line 20: mvn: command not found
build.sh: line 21: mvn: command not found
build.sh: line 22: mvn: command not found
build.sh: line 23: mvn: command not found
build.sh: line 24: mvn: command not found
build.sh: line 25: mvn: command not found
build.sh: line 26: cd: $'/home/admin/ORR\r/map-matching/\r': No such file or directory
build.sh: line 27: mvn: command not found
build.sh: line 28: mvn: command not found
```
I am pretty certain I have mvn installed as Graphhopper was working before trying to install OpenRailRouting. I am guessing the errors involving '\r' are a result of different encoding, but I don't know how to fix these.

Slightly at a loss at what to do, any ideas?

**Comment by Nakaner** [comment]
Windows is not officially supported because I do not use it. If you need to use this software on Windows, you do not have to install Cygwin to run `build.sh`. Instead, have a look into that script, see what it does and do the same with the Windows shell.

`mvn` is the Maven binary on Linux.

> Ran `git submodule add https://github.com/geofabrik/OpenRailRouting.git`, and `git submodule update`. Encountered the following error:
> ```error: Server does not allow request for unadvertised object d7497886bbb91b3cbb3
> 48465b1bd7308f5141ee0
> Fetched in submodule path 'graphhopper', but it did not contain d7497886bbb91b3c
bb348465b1bd7308f5141ee0. Direct fetching of that commit failed.```

That's not the correct way. GraphHopper is a submodule of this Git repository, not vice versa. Correct way:

* `git clone git@github.com:geofabrik/OpenRailRouting.git`
* `cd OpenRailRouting`
* `git submodule update --init`
