### ISSUE TITLE
PointNotFoundException - even point is valid

### ISSUE THREAD

**Issue by jolo2000** [geofabrik/OpenRailRouting#20]
Hi all,

I tried to get some railroad tracks outside of Germany, e.g. from Munich to Moscow.
Therefore I use the planet-xxx.osm.pbf, but I receive a PointNotFoundException error, even the location exists.

I assume it is related to the distance, e.g. 
Munich - Gdansk is found, 
Munich - Riga ( farther away) throws the PointNotFoundException.
Munich - Marseille found.
Munich - Madrid (farther away) not found

Is there any distance limit or threshold to configure in Grasshopper or OpenRailRouting to overcome this situation?
Any hints?
Johannes

ERROR [2020-07-10 13:26:23,586] com.graphhopper.resources.RouteResource: point=48.137108%2C11.575382&point=55.750446%2C37.617494&type=json&locale=en-US&vehicle=freight_diesel&weighting=fastest&elevation=false&key= 127.0.0.1 en_US Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:78.0) Gecko/20100101 Firefox/78.0 [48.137108,11.575382, 55.750446,37.617494], took:0.013820671, , fastest, freight_diesel, errors:[com.graphhopper.util.exceptions.PointNotFoundException: Cannot find point 1: 55.750446,37.617494]
INFO  [2020-07-10 13:26:23,586] com.graphhopper.http.MultiExceptionMapper: bad request: unknown reason

**Comment by Nakaner** [comment]
Riga and (partially) Madrid are not connected by the central European railway network at 1435 mm gauge. Therefore, this was a feature, not a bug.

OpenRailRouting has been rewritten in the past days and can be customize easily now. Therefore, I think this issue is resolved because gauge-agnostic routing is possible now.
