### ISSUE TITLE
Cannot traverse short 0V isolation sections between high-speed and conventional lines

### ISSUE THREAD

**Issue by overspeed21** [geofabrik/OpenRailRouting#27]
OpenRailRouting cannot traverse short 0V "isolation sections". These are marked on OSM in places like The Netherlands, between the transfer from high-speed to conventional. One example is near Hoofddorp. ![see image](https://user-images.githubusercontent.com/81588201/147680047-3f5295a1-f865-4955-a5b4-1ca437422961.png)

I am not knowledgeable enough to implement a solution, however I suppose a condition could be imposed in the route finding to account for momentum. So incorrect electrification wouldn't be excluded instantly, only once a certain distance has elapsed from the last compatible electrification section.

It is important to note that these sections (at least in NL) still have the `electrified:contact_line` tag, but both voltage and frequency are set to 0. So another potential solution could be a checkbox to specify whether electrified, but 0V sections should be included as if they were normally electrified

**Comment by Lunga26** [comment]
Hi overspeed21

If i may ask.  How did you run the basic demo ?

I am trying to get the demo running on Centos 7.6 .    I can build it but it doesnt run.

Can you please give me pointers or any tweaks that maybe necessary to get the basic demo running ...

Thank you.

**Comment by Nakaner** [comment]
This issue became invalid because the support for power systems has been moved to custom profiles. It is left to the authors of custom profiles to support grounded and neutral sections. The profiles included in OpenRailRouting should support it.
