### ISSUE TITLE
Frontend /maps 404 error

### ISSUE THREAD

**Issue by Jxlle** [geofabrik/OpenRailRouting#31]
Hi,

I followed the README, imported a map and started the server. Everything works except the frontend (/maps). I get a 404 error when visiting that page. Am I missing something?

Regards

**Comment by Nakaner** [comment]
There is currently no web frontend. For testing and client deployments, we have a simple web frontend but it has not been released yet.

The original [web frontend](https://github.com/geofabrik/graphhopper/tree/osm-reader-callbacks/web-bundle/src/main/resources/com/graphhopper/maps) of GraphHopper should work with the routing API.
