### ISSUE TITLE
turn restrictions routing vs. map-matching

### ISSUE THREAD

**Issue by palkooo** [geofabrik/OpenRailRouting#6]
Hi,
is it possible that the map-matching algorithm does not take into account turn restrictions by angle (or not so much) like classic routing does?
Example (left - routing, right - map matching):
![image](https://user-images.githubusercontent.com/1381893/43726842-895e5c92-99a0-11e8-997b-8a15bd549a4f.png)
Coordinates: 49.40771320279669,11.04756832122803 to 49.39492941352145,11.053726673126222

**Comment by Nakaner** [comment]
This is partially an upstream issue.

I can confirm this for the normal car routing compared to the map matching for cars. However, if you does map matching for cars, you are interested in the most likely route, not the most likely legal route. But the turn restrictions we create for railways are physical restrictions which cannot be broken without derailing.

**Comment by palkooo** [comment]
Thanks for the clarification. I can live with it, no problem, I was only curious.
